# Generated by Django 4.2.1 on 2023-11-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
