# Generated by Django 4.2.3 on 2023-12-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_locationid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='locationid',
        ),
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
