# Generated by Django 4.1.7 on 2023-08-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('locations', models.ManyToManyField(to='locations.location')),
            ],
            options={
                'verbose_name': '폴더',
                'verbose_name_plural': '폴더',
                'ordering': ['id'],
            },
        ),
    ]
