# Generated by Django 4.1.7 on 2023-08-22 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['-updated'], 'verbose_name': '폴더', 'verbose_name_plural': '폴더'},
        ),
        migrations.AddField(
            model_name='folder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
