# Generated by Django 4.1.7 on 2023-08-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': '장소', 'verbose_name_plural': '장소'},
        ),
    ]
